# Generated by Django 3.0.3 on 2020-05-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monit_id', models.CharField(max_length=32, unique=True)),
                ('monit_version', models.TextField(null=True)),
                ('localhostname', models.TextField(null=True)),
                ('uptime', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.TextField(null=True)),
                ('status_hint', models.IntegerField(null=True)),
                ('monitor', models.IntegerField(null=True)),
                ('monitormode', models.IntegerField(null=True)),
                ('pendingaction', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('release', models.TextField(null=True)),
                ('version', models.TextField(null=True)),
                ('machine', models.TextField(null=True)),
                ('cpu', models.IntegerField(null=True)),
                ('memory', models.IntegerField(null=True)),
                ('swap', models.IntegerField(null=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='monitcollector.Server')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitcollector.Service')),
                ('date_last', models.PositiveIntegerField(null=True)),
                ('date', models.TextField(null=True)),
                ('load_avg01_last', models.FloatField(null=True)),
                ('load_avg01', models.TextField(null=True)),
                ('load_avg05_last', models.FloatField(null=True)),
                ('load_avg05', models.TextField(null=True)),
                ('load_avg15_last', models.FloatField(null=True)),
                ('load_avg15', models.TextField(null=True)),
                ('cpu_user_last', models.FloatField(null=True)),
                ('cpu_user', models.TextField(null=True)),
                ('cpu_system_last', models.FloatField(null=True)),
                ('cpu_system', models.TextField(null=True)),
                ('cpu_wait_last', models.FloatField(null=True)),
                ('cpu_wait', models.TextField(null=True)),
                ('memory_percent_last', models.FloatField(null=True)),
                ('memory_percent', models.TextField(null=True)),
                ('memory_kilobyte_last', models.PositiveIntegerField(null=True)),
                ('memory_kilobyte', models.TextField(null=True)),
                ('swap_percent_last', models.FloatField(null=True)),
                ('swap_percent', models.TextField(null=True)),
                ('swap_kilobyte_last', models.PositiveIntegerField(null=True)),
                ('swap_kilobyte', models.TextField(null=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='monitcollector.Server')),
            ],
            bases=('monitcollector.service',),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitcollector.Service')),
                ('date_last', models.PositiveIntegerField(null=True)),
                ('date', models.TextField(null=True)),
                ('pid', models.IntegerField(null=True)),
                ('ppid', models.IntegerField(null=True)),
                ('uptime', models.PositiveIntegerField(null=True)),
                ('children', models.PositiveIntegerField(null=True)),
                ('cpu_percenttotal_last', models.FloatField(null=True)),
                ('cpu_percenttotal', models.TextField(null=True)),
                ('memory_percenttotal_last', models.FloatField(null=True)),
                ('memory_percenttotal', models.TextField(null=True)),
                ('memory_kilobytetotal_last', models.PositiveIntegerField(null=True)),
                ('memory_kilobytetotal', models.TextField(null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitcollector.Server')),
            ],
            bases=('monitcollector.service',),
        ),
    ]
